I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 37, in script
    show carga() with dissolve
Exception: Image 'carga' does not accept attributes '()'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 37, in script
    show carga() with dissolve
  File "F:\renpy-8.3.4-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "F:\renpy-8.3.4-sdk\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "F:\renpy-8.3.4-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "F:\renpy-8.3.4-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "F:\renpy-8.3.4-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "F:\renpy-8.3.4-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'carga' does not accept attributes '()'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
School idol diary Visual Novel 0.4
Wed Apr 30 18:21:38 2025
