I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 593, in script
    scene estacion with recuerdo
  File "game/script.rpy", line 593, in <module>
    scene estacion with recuerdo
NameError: name 'recuerdo' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 593, in script
    scene estacion with recuerdo
  File "F:\renpy-8.3.4-sdk\renpy\ast.py", line 1370, in execute
    paired = renpy.python.py_eval(self.paired)
  File "F:\renpy-8.3.4-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "F:\renpy-8.3.4-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 593, in <module>
    scene estacion with recuerdo
NameError: name 'recuerdo' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
School idol diary Visual Novel 0.4
Sat Apr 26 12:59:38 2025
